[auth]
enable_signup = true

[functions.dispatch_b2c_otp]
enabled = true
verify_jwt = false
import_map = "./functions/dispatch_b2c_otp/deno.json"
entrypoint = "./functions/dispatch_b2c_otp/index.ts"

[functions.convite_digital]
enabled = true
verify_jwt = false
import_map = "./functions/convite_digital/deno.json"
entrypoint = "./functions/convite_digital/index.ts"

[auth.email.template.magic_link]
subject = "Código de Acesso Admin - Lenis Funpark"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.confirmation]
subject = "Código de Acesso Admin - Lenis Funpark"
content_path = "./supabase/templates/confirmation.html"