ALTER TABLE reservas
ADD COLUMN IF NOT EXISTS nome_aniversariante VARCHAR(255),
ADD COLUMN IF NOT EXISTS convite_lenis BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS extras BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS decoracao BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS notas_adicionais TEXT,
ADD COLUMN IF NOT EXISTS termos_veracidade BOOLEAN DEFAULT false;
